# @package model.transform

_target_: model.transforms.WaveletTransform

wavelet: 'morl'
min_freq: 0.3
max_freq: 50.0
n_scales: 100
highlight_transient: false
transient_weight: 0.0
img_size: ${global.img_size}
interpolate: false
