# @package model.head

_target_: model.heads.RNNHead
input_dim: ${model.backbone.embed_dim}
rnn_type: 'GRU'
rnn_layers: 1
rnn_hidden_mult: 2
num_classes: 2
dropout: 0.1
sequence_output: false
bidirectional: true
input_seq_len: 20
