# @package model

defaults:
  - preprocessors: minimal
  - signal_augmentor: default
  - transform: wavelet
  - spectral_augmentor: null
  - backbone: fogformer
  - head: gru_sequence_binary
  - _self_

img_size: ${global.img_size}
num_classes: 2
