# @package model

defaults:
  - preprocessors: minimal
  - signal_augmentor: null
  - transform: raw
  - spectral_augmentor: null
  - backbone: fogformer
  - head: identity
  - _self_

mask_ratio: 0.75
mask_mode: "temporal"
ema_decay: 0.996
ema_decay_end: 0.9999
