# @package train.loss

_target_: model.losses.JointLoss
losses:
  - target: model.losses.WeightedCrossEntropyLoss
    weight: 0.5
    compute_class_weights: true
    reduction: mean
  - target: model.losses.SoftDiceLoss
    weight: 0.5
    smooth: 1.0e-6
    reduction: mean
