defaults:
  - optimizer: adamw
  - scheduler: cosine
  - loss: jepa
  - callbacks: pretraining
  - logger: pretraining
  - logging: pretraining
  - registry: default
  - task_manager: jepa
  - trainer: fog_mae
  - _self_

pipeline_target: pipeline.jepa.JEPAPipeline
pipeline_type: "jepa"

optimizer:
  lr: 1.5e-4

callbacks:
  checkpoint:
    dirpath: "./checkpoints/jepa"

registry:
  monitor_metric: "losses/val_loss"
  monitor_mode: "min"
