defaults:
  - optimizer: adamw
  - scheduler: cosine
  - loss: mae
  - callbacks: pretraining
  - logger: pretraining
  - logging: pretraining
  - registry: default
  - task_manager: mae
  - trainer: fog_mae
  - _self_

pipeline_type: "mae"

optimizer:
  lr: 1.5e-4

callbacks:
  checkpoint:
    dirpath: "./checkpoints/mae"

registry:
  monitor_metric: "losses/val_loss"
  monitor_mode: "min"
